spring:
  application:
    name: shop

  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000